### ISSUE TITLE
Flashlight and getUserMedia

### ISSUE THREAD

**Issue by tobeee** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#16]
Hiya -  got a quick question. I am currently using getUserMedia to grab the camera canvas (using Crosswalk-powered Chromium) and wanted to add the ability to use the flash.

I tried using the plugin - which works, but when getUserMedia is called it no-longer works. I imagine this might be to do with the device only allowing one program to access the camera, though technically they are doing separate things (ie the flash and the camera itself) I could definitely see how this might be an issue!

Has anyone had any luck getting both to work?

**Comment by andrewthecoder** [comment]
I'm keen to solve this problem too - I've built a photo capture screen in our app using getUserMedia and canvas, but the client has just asked for the ability to turn the flash on and I've suddenly realised that's a tricky one to solve as Android only allows one access of the camera API so I can't have the flashlight on while streaming the camera.

Any suggestions?

**Comment by tobeee** [comment]
I've found no solution using gUM but I think there might be another. It's a
lot trickier though - this plugin
https://github.com/donaldp24/CanvasCameraPlugin uses an approach that
should work. Camera access is piped direct to canvas, so you've got access
to the flashlight too.

However - I've not tried the plugin yet... my feeling is it might need work
as I looked at a few issues. Take a look perhaps? Would be interested to
hear your thoughts

On Thu, Jan 8, 2015 at 4:14 PM, Andrew Beveridge <notifications@github.com>
wrote:

> I'm keen to solve this problem too - I've built a photo capture screen in
> our app using getUserMedia and canvas, but the client has just asked for
> the ability to turn the flash on and I've suddenly realised that's a tricky
> one to solve as Android only allows one access of the camera API so I can't
> have the flashlight on while streaming the camera.
>
> Any suggestions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EddyVerbruggen/Flashlight-PhoneGap-Plugin/issues/16#issuecomment-69202717>
> .
>



-- 
Toby Green

**Comment by SMERKY** [comment]
Hey Guys,

We are running into the same problem! Did anyone find a fix for this issue?

Cheers

**Comment by tobeee** [comment]
Gave up I'm afraid :(

On Mon, Apr 6, 2015 at 12:43 AM, Aaron Leggett <notifications@github.com>
wrote:

> Hey Guys,
>
> We are running into the same problem! Did anyone find a fix for this issue?
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EddyVerbruggen/Flashlight-PhoneGap-Plugin/issues/16#issuecomment-89869507>
> .
>



-- 
Toby Green

**Comment by EddyVerbruggen** [comment]
Hey guys, sorry I haven't had the chance to look into this issue. I was hoping someone would step up and send a PR. I hope to revisit this issue somewhere in the near future.

**Comment by andrewthecoder** [comment]
My work (as in, me!) will probably be tackling this properly in the next couple of weeks so if Eddy doesn't get a chance to tackle it, don't get disheartened! :)

**Comment by andrewthecoder** [comment]
For anyone who's still following this, there's actually been a huge amount of development work by mcasas in chromium recently to implement the MediaStream Image Capture spec.
The FillLightMode part of this spec (https://w3c.github.io/mediacapture-image/index.html#filllightmode) will should resolve this issue once implemented.

You can follow the progress here: https://bugs.chromium.org/p/chromium/issues/detail?id=518807

I believe this is likely to be live functionality in chromium (and thus, Crosswalk) within a few months.
