### ISSUE TITLE
startPreview Failed

### ISSUE THREAD

**Issue by AndersonMamede** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#22]
I have an app which when a button is pressed, it should blink the flashlight (1second on, 0.5s off, 1s on, 0.5s off, 1s on, 0.5s off...) until the button is pressed again. The problem is, after some time (1 minute or so), it throws an error "startPreview failed", the flashlight crashes and then every call to switchOn/switchOff/toggle throws "Fail to connect to camera service" until the app is restarted.

The only way to make it work without crashing is removing the following line from Flashlight.java:

mCamera.startPreview();

That way, everything seems to be fine.

I've read Android documentation http://developer.android.com/reference/android/hardware/Camera.html#startPreview() and I'm not sure if that is required for flashlight to work.

Has anyone had the same problem?

I'm testing on Android 5.0.2.

**Comment by EddyVerbruggen** [comment]
That line was added as a PR because it didn't work back then. Perhaps it works without it on Android 5 but that should be investigated.
