### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by dalisoft** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#23]
Hi @EddyVerbruggen!
I know this is not a plugin issue, but think anyone can help who reading this issue!
I'm using PhoneGap Desktop App (Windows 10 Pro x86), works normally, but not working external plugins like Flashlight. I can fix this issue?

**Comment by EddyVerbruggen** [comment]
Hi @dalisoft, I am not in any way part of the Apache team (not counting a commit to their repo's here and there), so please [head over to their project repo](https://github.com/phonegap/phonegap-app-desktop/issues).

The answer will be: we only support the Apache 'core' plugins, not any third party plugins like the Flashlight plugin. Browse their issues though and perhaps even open one yourself if you can't find a satisfactory answer.

Cheers,
Eddy
