### ISSUE TITLE
Not found Camera

### ISSUE THREAD

**Issue by amirudin** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#25]
Hi @EddyVerbruggen 

Someone report a problem here. Can you help?
http://gsfn.us/t/4qtbn

Thanks.

**Comment by EddyVerbruggen** [comment]
Hi @amirudin, asked the user to come over here, thanks for letting me know!

I'm going to require some more details and if possible the app itself so I can look at the code.

**Comment by evertonm** [comment]
I'm asked from community phonegap. I tried acess camera to take a picture with Flashlight on. But i acess, the application stop running.

**Comment by evertonm** [comment]
I'm using your plugin Flashlight with plugin Camera Cordova.

**Comment by EddyVerbruggen** [comment]
@evertonm see my question above :)

**Comment by evertonm** [comment]
@EddyVerbruggen I sent email for you because don't up files(index and camera files) here. You can help me?

**Comment by EddyVerbruggen** [comment]
Handling this by email.
