### ISSUE TITLE
Strobe light issue.

### ISSUE THREAD

**Issue by zocheyado** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#27]
So I was attempting to use the plugin to create a strobe light effect. However It seems that there is some sort of minimum time for turning on and off the flashlight (seems to be about a second), does anyone know if this is a limitation of Cordova or if there is something I am missing.

**Comment by EddyVerbruggen** [comment]
You're referring to Android, right? On iOS I found it to work quite well.

I'm guessing it's some kind of hardware protection, or otherwise general Android internal slowness, not a Cordova issue because that JS-Native bridge is lightning fast.

**Comment by zocheyado** [comment]
No this was on iPhone 6, it actually seemed faster on android. Is there anyway I could determine the bottleneck?

**Comment by EddyVerbruggen** [comment]
Can you share your algorithm?
And how slow is slow exactly (ms)?

**Comment by KrisKlip** [comment]
I am having the same issue. 
It seems to be a minimum delay of around 500ms.
I am using a Samsung Galaxy S4 with Android 4.4.4
