### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by Joeeeeh7** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#28]
Hello Eddy,

It seems like i just can't get your plugin to work. Not even on a very basic phonegap installation with the Desktop app. Could you please make me a very basic working example with just a toggle button which does work for you? Would really appreciate it!

**Comment by EddyVerbruggen** [comment]
with the desktop app your app essentially runs inside their companion app, right? Then this plugin won't be available.. you need to install it as a standalone app.

**Comment by Joeeeeh7** [comment]
So it only works when you build the app and install it on a real device?

**Comment by EddyVerbruggen** [comment]
A simulator can't flash, a companion app doesn't have the plugin bundled, so yes.
