### ISSUE TITLE
ios9 and Andriod 4.0 + issues

### ISSUE THREAD

**Issue by mrwrighty** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#29]
Hi 

I have implemented the flashlight during a barcode scan. The light is set to time out after 8 seconds.

Flashlight works fine on iOS9 on iPhone 5s but does not work at all on iOS9 iPhone 6s, sorry cannot check any other iOS device. No error shown.

Flashlight lights on Android works on some Android 4.0+ devices but not others. When it works the light  stays on after an error Sorry the Android Camera encountered a problem. You may need to restart your device. Even if the light does not light the same error appears in Android.

Building with Corodova 4.1.2

**Comment by noobiedev** [comment]
Hi, did you manage to find a solution for this? I haven't tested on another device yet but seems like it's not working on iPhone 6s Plus.

**Comment by mrwrighty** [comment]
Implemented a check on device so Android uses the volume up and down to turn the light on and off. I use the toggle option for other devices which seems ok

**Comment by noobiedev** [comment]
thanks for the response.  Can you please share your code?

That's what I'm thinking too:

1. create toggle button 
2. if toggle = true then turn on flash light before calling the scan function

however, i can't get it to work and having issues debugging.

**Comment by noobiedev** [comment]
Anyone have a solution for iOS?

**Comment by EddyVerbruggen** [comment]
You can't combine this with the barcode scanner plugin - that plugin should offer a mechanism to tap into the flashlight.
