### ISSUE TITLE
Not a cordova project

### ISSUE THREAD

**Issue by v1rt** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#32]
I got this error when I ran cordova plugin add cordova-plugin-flashlight and I ran it inside the project directory

```
Error: Current working directory is not a Cordova-based project.
```

**Comment by EddyVerbruggen** [comment]
So that's a Cordova error, not a plugin error, right? Please post this on SO.

**Comment by v1rt** [comment]
I got it working. I was wrong because I use 'git clone' instead. I also posted an issue in so since I couldn't figure out how to start a cordova application. It's not related to your project. Thanks.

**Comment by EddyVerbruggen** [comment]
:+1:  good job!

**Comment by c0debreaker** [comment]
Hi Eddy,

Can you help me? I couldn't figure out why my build is failing. I created a stackoverflow question.
http://stackoverflow.com/questions/34445338/my-first-phonegap-app-flashlight-is-failing-on-cordova-build

Thanks!

**Comment by EddyVerbruggen** [comment]
Answered on SO.
