### ISSUE TITLE
Plugin not woking with ios

### ISSUE THREAD

**Issue by Balaji-Gopal** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#34]
I am using Ionic framework with Cordova, Flashlight is not working with ios, It only works with android phones. Is there any ios platform depends things need to be written?

Steps that i followed to implement:
1)I have added the below xml in config.xml

<gap:plugin name="cordova-plugin-flashlight" source="npm" />

2)On Click of button i m Invoking this function

window.plugins.flashlight.available(function(isAvailable) {
  if (isAvailable) {
    window.plugins.flashlight.toggle();
  } else {
    alert("Flashlight not available on this device");
  }
});

**Comment by EddyVerbruggen** [comment]
Should work fine for iOS, did you try a new Cordova CLI project to confirm this?

**Comment by Balaji-Gopal** [comment]
Yes I did try with Cordova CLI also,I dont see any toggle function in the plugin source code,I only see toggle function in android source code. I think for windows and ios I need to make use switchOn() and switchOff().

**Comment by EddyVerbruggen** [comment]
That's what the JS bridge actually does for you. Check this: https://github.com/EddyVerbruggen/Flashlight-PhoneGap-Plugin/blob/master/www/Flashlight.js#L24-L30
