### ISSUE TITLE
SAMSUNG FLASHING IS SUPER DELAY THAN OTHERS DEVICES

### ISSUE THREAD

**Issue by yydad117** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#43]
I need your help.

I have tested the plugin, I love it.
However, I tested into many devices, including samsung devices and other devices. 
I will set the flashing on, then set a timeout delay about, 300ms, then it will turn off automatically.

Other devices work very well, however, the SAMSUNG type doesn't work very well. It give a very large delay after turn on, off, then next comments. 

I have tried debugged it for about 2-3 days, but still don't know what's wrong.
Thanks for your help.

**Comment by EddyVerbruggen** [comment]
Could be internal to the device.. can you try with other apps and see if they have a similar delay?

**Comment by yydad117** [comment]
I tried with LG and ASUS, they blink with a reasonable speed. 
However, with Samsung, it blinks very slow and has an app crash all the time. 
It said the camera is used after released, then the app crash.
The app crash sometimes happened in LG and ASUS.

**Comment by yydad117** [comment]
Can help?

**Comment by EddyVerbruggen** [comment]
No not really if it's down to the hardware..
