### ISSUE TITLE
Not available for android 6.0

### ISSUE THREAD

**Issue by sabirali007** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#44]
it not working on my android 6.0

**Comment by Unmihai** [comment]
Confirm. not working for me either:(

**Comment by Unmihai** [comment]
Hello, i managed to make it work by changing the android:targetSdkVersion from 23 to 22. 
It`s not the best way of solving this issue but it works for now. If you want to "really" fix it you should check the way android asks for permissions in android 6.0 and above.

thank you

**Comment by EddyVerbruggen** [comment]
Do you ever get the permission prompt?

**Comment by sabirali007** [comment]
Thanks Unmihai :)

**Comment by Unmihai** [comment]
@EddyVerbruggen  it asks for permissions when you install the app. It`s not a natural behavior for android 6 but it works and google approves it: https://play.google.com/store/apps/details?id=lanterna.flash.com

As I said before this is just a way of temporary fixing this issue and I will try to do a real fix and come back with an update.

Thanks!

**Comment by EddyVerbruggen** [comment]
@Unmihai Thanks. With API level 23 on Android 6 you should get the permission prompt when switching the Flashlight on [the first time](https://github.com/EddyVerbruggen/Flashlight-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/Flashlight.java#L64). Don't you see that prompt?

**Comment by Unmihai** [comment]
@EddyVerbruggen no, you don t get that prompt. So basically if you use api 23 you can install the app but nothing happens on android 6 because there s no asking for permission not on install and not on use:).

**Comment by EddyVerbruggen** [comment]
OK, would be cool if you could debug that line I highlighted in my previous comment.
