### ISSUE TITLE
Flashlight Plugin Deletes and Recreates cordova_plugins.js losing earlier plugin installs.

### ISSUE THREAD

**Issue by jackhschwartz** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#50]
The Flashlight-PhoneGap-Plugin deletes and Recreates cordova_plugins.js losing earlier plugin installs.

Example:  
1. First installed the barcodescanner plugin.  Here is the resulting cordova_plugs.js:

cordova.define('cordova/plugin_list', function(require, exports, module) {
module.exports = [
    {
        "file": "plugins/phonegap-plugin-barcodescanner/www/barcodescanner.js",
        "id": "phonegap-plugin-barcodescanner.BarcodeScanner",
        "clobbers": [
            "cordova.plugins.barcodeScanner"
        ]
    }
];
module.exports.metadata = 
// TOP OF METADATA
{
    "phonegap-plugin-barcodescanner": "6.0.3"
}
// BOTTOM OF METADATA
});

2. Then installed flashlight plugin. Here is the resulting cordova_plugs.js:

cordova_plugins.js:cordova.define('cordova/plugin_list', function(require, exports, module) {
module.exports = [
    {
        "id": "cordova-plugin-flashlight.Flashlight",
        "file": "plugins/cordova-plugin-flashlight/www/Flashlight.js",
        "pluginId": "cordova-plugin-flashlight",
        "clobbers": [
            "window.plugins.flashlight"
        ]
    }
];
module.exports.metadata = 
// TOP OF METADATA
{
    "cordova-plugin-whitelist": "1.3.0",
    "cordova-plugin-flashlight": "3.2.0"
};
// BOTTOM OF METADATA
});

Thus the barcodescanner plugin was lost and was not re-installable either!

**Comment by EddyVerbruggen** [comment]
Guess this was a glitch as no one else responded.
